os: Visual Studio 2015
clone_folder: c:\projects\DeepTags

environment:
  matrix:
  - name: win32_msvc2015
    arch: x86
    qt: C:\Qt\5.11.3\msvc2015\bin

  - name: win64_msvc2015
    arch: amd64
    qt: C:\Qt\5.11.3\msvc2015_64\bin

cache:
    - C:\Program Files (x86)\Inno Setup 5


install:
    - if not exist "C:\Program Files (x86)\Inno Setup 5" choco install innosetup
    - set PATH=C:\Program Files (x86)\\Inno Setup 5;%PATH%
    - set PATH=%PATH%;%qt%
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch%


before_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - git submodule update --init --recursive
    - qmake -config release


build_script:
    - nmake
    - cd packaging && mkdir DeepTags && cd DeepTags
    - copy ..\..\deeptags.exe .
    - copy ..\..\LICENSE .
    - copy ..\..\images\DeepTags.ico .
    - mkdir translations && copy ..\..\locale\*.qm translations\
    - windeployqt.exe . --no-compiler-runtime

    - if %arch%==x86 copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\msvcp140.dll" .
    - if %arch%==x86 copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT\vcruntime140.dll" .
    - if %arch%==x86 copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86\*.dll" .
    - if %arch%==x86 iscc %APPVEYOR_BUILD_FOLDER%\packaging\win_inno_32bit.iss

    - if %arch%==amd64 copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\msvcp140.dll" .
    - if %arch%==amd64 copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\vcruntime140.dll" .
    - if %arch%==amd64 copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\*.dll" .
    - if %arch%==amd64 iscc %APPVEYOR_BUILD_FOLDER%\packaging\win_inno_64bit.iss


after_build:
    - cd %APPVEYOR_BUILD_FOLDER%\packaging
    - if %arch%==amd64 7z a DeepTags-win-64bit.zip %APPVEYOR_BUILD_FOLDER%\packaging\DeepTags
    - if %arch%==x86   7z a DeepTags-win-32bit.zip %APPVEYOR_BUILD_FOLDER%\packaging\DeepTags
    - dir


artifacts:
- path: packaging\DeepTags_setup-64bit.exe
  name: DeepTags_setup-64bit.exe
- path: packaging\DeepTags_setup-32bit.exe
  name: DeepTags_setup-32bit.exe
- path: packaging\DeepTags-win-64bit.zip
  name: DeepTags-win-64bit.zip
- path: packaging\DeepTags-win-32bit.zip
  name: DeepTags-win-32bit.zip

deploy:
- provider: GitHub
  release: $(appveyor_repo_tag_name)
  auth_token:
    secure: 3MtVN4ezpTjkn9g64kcNASvLF8N3n5FoMd+Z5M3tLHnPgLrFu530Wa/FhuVtg1mm
  repository: SZinedine/DeepTags
  artifact:
    DeepTags_setup-64bit.exe
    DeepTags_setup-32bit.exe
  on:
    APPVEYOR_REPO_TAG: true
  draft: false
  prerelease: true
  force_update: false
