language: cpp
compiler: gcc
os: linux
dist: trusty


jobs:
  include:
    - os: linux
      dist: trusty
      env: DIST=trusty
    - os: linux
      dist: xenial
      env: DIST=xenial
    - os: linux
      dist: bionic
      env: DIST=bionic

before_install:
- echo "building in $DIST"
- if [ "$DIST" == "trusty" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test && sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty ; fi
- sudo apt-get update -qq


install:
- if [ "$DIST" == "trusty" ]; then sudo apt-get install -qq tree qt510-meta-minimal libgl1-mesa-dev g++-9 ; fi
- if [ "$DIST" == "trusty" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 ; fi
- if [ "$DIST" == "trusty" ]; then source /opt/qt5*/bin/qt5*-env.sh ; fi
- if [ "$DIST" != "trusty" ]; then sudo apt-get install -qq tree libgl1-mesa-dev g++ qt5-default qt5-qmake ; fi

before_script:
- git submodule update --init --recursive
- qmake


script:
- make -j$(nproc)
- cd packaging/
- if [ "$DIST" == "trusty" ]; then wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage ; fi
- if [ "$DIST" == "trusty" ]; then chmod +x linuxdeployqt-*.AppImage && ./appimage.sh --add-libstdc++ ; fi
- if [ "$DIST" != "trusty" ]; then ./deb.sh ; fi
- pwd && tree . && cd ..


deploy:
  provider: releases
  draft: false
  edge: true
  cleanup: false
  token: $GITHUB_TOKEN
  file_glob: true
  file:
    - packaging/DeepTags*.AppImage
    - packaging/DeepTags*.AppImage.zsync
    - packaging/deeptags_*.deb
  on:
    repo: SZinedine/DeepTags
    tags: true
