language: cpp
compiler: gcc
os: linux
dist: xenial

services:
- docker

jobs:
  include:
    - os: linux
      dist: xenial
      env: DIST=xenial
    - os: linux
      dist: bionic
      env: DIST=bionic
    - os: linux
      dist: focal
      env: DIST=focal
    - os: linux
      dist: xenial
      env: DIST=archlinux


# see: https://github.com/mikkeloscar/arch-travis
archlinux:
  packages:
  - qt5-base
  - qt5-svg
  - qt5-tools
  - make
  - gcc
  - tree
  - curl
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  script:
  - echo "building inside the arch image"
  - cd packaging && makepkg -p PKGBUILD-travis
#  - timeout 30s curl --upload-file *.pkg.tar.zst https://transfer.sh/deeptags.pkg.tar.zst > tmp_ && cat tmp_ && echo ""
  - cd ..


before_install:
- echo "building in $DIST"
- sudo apt-get update -qq


install:
- if [ "$DIST" == "bionic" ] || [ "$DIST" == "xenial" ] || [ "$DIST" == "focal" ]; then
    sudo apt-get install -qq libgl1-mesa-dev g++ qt5-default qt5-qmake ;
  fi
- sudo apt-get install -qq tree


before_script:
- git submodule update --init --recursive
- if [ "$DIST" != "archlinux" ]; then qmake ; fi


script:
- if [ "$DIST" != "archlinux" ]; then
    make -j$(nproc) ;
    cd packaging/ ;
  fi
- if [ "$DIST" == "bionic" ] || [ "$DIST" == "xenial" ] || [ "$DIST" == "focal" ]; then
    ./deb.sh ;
  fi
- if [ "$DIST" == "archlinux" ]; then
    curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash ;
  fi
- cd "$TRAVIS_BUILD_DIR" && ls -lhXkN packaging/


deploy:
  provider: releases
  draft: false
  edge: true
  cleanup: false
  token: $GITHUB_TOKEN
  file_glob: true
  file:
    - packaging/DeepTags*.AppImage
    - packaging/DeepTags*.AppImage.zsync
    - packaging/deeptags_*.deb
    - packaging/deeptags-*.pkg.tar.xz
  on:
    repo: SZinedine/DeepTags
    tags: true
