name: Running Tests


on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  BUILD_TYPE: Debug
  BUILD_DIR: ${{github.workspace}}/build
  QT_LOC: ${{github.workspace}}/Qt
  QT_VERSION: 5.12.2
  QT_ARCH: gcc_64


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"


    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{env.QT_LOC}}
        key: ${{runner.os}}-${{env.QT_ARCH}}-QtCache-${{env.QT_VERSION}}

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 5.15.2
        dir: ${{env.QT_LOC}}
        arch: gcc_64
        aqtversion: '==3.1.11'
        setup-python: false
        cache: true


    - name: Configure CMake for testing
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBENCHMARK=ON -DTEST=ON 


    - name: Build for testing
      run: |
        cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel $(nproc)


    - name: Re-Configure CMake for regular build
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBENCHMARK=ON -DTEST=OFF 


    - name: Launch a regular build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel $(nproc)

